Repository glutter-dev-team/glutter, pull requests merged in 2020-12, with the labels that each got.

#84 System-Infos auf Dashboard
  lib/models/monitoring/pluginsList.dart
  lib/models/monitoring/system.dart
  lib/screens/dashboard/dashboard_screen.dart
  lib/screens/monitoring/data_list_builder.dart
  lib/screens/monitoring/monitoring_screen.dart
  lib/screens/settings/manage_profiles/profile_create_screen.dart
  lib/screens/settings/manage_profiles/profile_list_screen.dart
  lib/services/monitoring/glances_service.dart
  lib/utils/utils.dart
  lib/widgets/errors.dart
Labels: enhancement

#85 Fehlermeldung für inexistente Profile implementiert
  lib/screens/dashboard/dashboard_screen.dart
  lib/screens/monitoring/monitoring_screen.dart
  lib/screens/remote_control/remote_control_screen.dart
  lib/services/shared/database_provider.dart
  lib/services/shared/database_service.dart
  lib/widgets/errors.dart
Labels: enhancement

#86 Monitoring-Screen überarbeitet
  assets/fonts/RobotoMono-Regular.ttf
  lib/screens/monitoring/monitoring_data_list_builder.dart
  lib/screens/monitoring/monitoring_screen.dart
  lib/screens/monitoring/tabs/cpu_tab.dart
  lib/screens/monitoring/tabs/memory_tab.dart
  lib/screens/monitoring/tabs/network_tab.dart
  lib/screens/monitoring/tabs/sensors_tab.dart
  lib/screens/remote_control/command_create_screen.dart
  lib/screens/remote_control/remote_control_screen.dart
  lib/services/remote_control/remote_service.dart
  lib/utils/utils.dart
  lib/widgets/async.dart
  lib/widgets/dialogs.dart
  lib/widgets/errors.dart
  pubspec.yaml
Labels: bug, enhancement, high prio

#87 Doc-Strings hinzugefügt und ein bisschen Refactoring/Aufräumen
  lib/main.dart
  lib/screens/monitoring/monitoring_data_list_builder.dart
  lib/screens/monitoring/monitoring_screen.dart
  lib/screens/monitoring/tabs/cpu_tab.dart
  lib/screens/monitoring/tabs/memory_tab.dart
  lib/screens/monitoring/tabs/network_tab.dart
  lib/screens/monitoring/tabs/sensors_tab.dart
  lib/screens/remote_control/remote_control_screen.dart
  lib/screens/remote_control/widgets/command_result.dart
  lib/screens/settings/manage_profiles/widgets/dialogs.dart
  lib/utils/utils.dart
  lib/widgets/async.dart
  lib/widgets/dialogs.dart
  lib/widgets/errors.dart
  lib/widgets/profile_selector.dart
  test/widget_test.dart
Labels: documentation

#88 Version 1.0.0 gesetzt + Refactoring und Kommentare
  lib/models/monitoring/memory.dart
  lib/models/monitoring/system.dart
  lib/models/remote_control/command.dart
  lib/models/settings/settings.dart
  lib/models/shared/profile.dart
  lib/screens/dashboard/dashboard_screen.dart
  lib/screens/monitoring/monitoring_data_list_builder.dart
  lib/screens/monitoring/monitoring_screen.dart
  lib/screens/monitoring/tabs/cpu_tab.dart
  lib/screens/monitoring/tabs/memory_tab.dart
  lib/screens/monitoring/tabs/network_tab.dart
  lib/screens/monitoring/tabs/sensors_tab.dart
  lib/screens/remote_control/command_create_screen.dart
  lib/screens/remote_control/remote_control_screen.dart
  lib/screens/settings/about_screen.dart
  lib/screens/settings/manage_profiles/profile_create_screen.dart
  lib/screens/settings/manage_profiles/profile_edit_screen.dart
  lib/screens/settings/manage_profiles/profile_list_screen.dart
  lib/screens/settings/manage_profiles/widgets/profile_form_widgets.dart
  lib/screens/settings/settings_screen.dart
  lib/services/shared/database_provider.dart
  lib/services/shared/database_service.dart
  lib/utils/routes.dart
  lib/utils/utils.dart
  lib/widgets/drawer.dart
  pubspec.lock
Labels: Technical, documentation
